### PR TITLE
Daniel carter week 2 website

### PR DESCRIPTION
**Pull request by carterd888**
my attempt to recreate the website layout without using inspect just based on observation.

### CODE REVIEW

**Review by Codeama — COMMENTED** [review]
Are you still working on this @carterd888 ? It seems incomplete or am I looking at the wrong files?

**Comment by carterd888** [comment]
> Are you still working on this @carterd888 ? It seems incomplete or am I looking at the wrong files?

the files i changed are here:

https://github.com/carterd888/HTML-CSS-Homework/tree/daniel-carter-week-2-website/week2/2-website

**Comment by Codeama** [comment]
> > Are you still working on this @carterd888 ? It seems incomplete or am I looking at the wrong files?
> 
> the files i changed are here:
> 
> https://github.com/carterd888/HTML-CSS-Homework/tree/daniel-carter-week-2-website/week2/2-website

This is what I see when I run the files locally:

Screenshot 2020-06-07 at 06 54 28

**Comment by carterd888** [comment]
image

this is what i see from my screen, is it worth making another pull request?

**Pull request closed without merging**
